import type { Provider } from './types';

export const DEFAULT_PROVIDERS: Provider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    slug: 'openai',
    type: 'direct',
    baseUrl: 'https://api.openai.com/v1',
    models: ['gpt-4', 'gpt-4-turbo', 'gpt-3.5-turbo'],
    apiKeyAlias: 'OPENAI_API_KEY',
    getKeyUrl: 'https://platform.openai.com/api-keys',
    notes: 'OpenAI GPT models',
  },
  {
    id: 'google',
    name: 'Google Gemini',
    slug: 'google',
    type: 'direct',
    baseUrl: 'https://generativelanguage.googleapis.com/v1',
    models: ['gemini-pro', 'gemini-pro-vision'],
    apiKeyAlias: 'GOOGLE_API_KEY',
    getKeyUrl: 'https://aistudio.google.com/app/apikey',
    notes: 'Google Gemini models',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    slug: 'anthropic',
    type: 'direct',
    baseUrl: 'https://api.anthropic.com/v1',
    models: ['claude-3-opus', 'claude-3-sonnet', 'claude-3-haiku'],
    apiKeyAlias: 'ANTHROPIC_API_KEY',
    getKeyUrl: 'https://console.anthropic.com',
    notes: 'Anthropic Claude models',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    slug: 'mistral',
    type: 'direct',
    baseUrl: 'https://api.mistral.ai/v1',
    models: ['mistral-large', 'mistral-medium', 'mistral-small'],
    apiKeyAlias: 'MISTRAL_API_KEY',
    getKeyUrl: 'https://console.mistral.ai',
    notes: 'Mistral AI models',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    slug: 'cohere',
    type: 'direct',
    baseUrl: 'https://api.cohere.ai/v1',
    models: ['command', 'command-light'],
    apiKeyAlias: 'COHERE_API_KEY',
    getKeyUrl: 'https://dashboard.cohere.com/api-keys',
    notes: 'Cohere models',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    slug: 'openrouter',
    type: 'openrouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    models: [],
    apiKeyAlias: 'OPENROUTER_API_KEY',
    getKeyUrl: 'https://openrouter.ai/keys',
    notes: 'OpenRouter unified API',
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    slug: 'azure',
    type: 'azure',
    models: [],
    apiKeyAlias: 'AZURE_OPENAI_API_KEY',
    getKeyUrl: 'https://portal.azure.com',
    notes: 'Azure OpenAI Service',
  },
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    slug: 'bedrock',
    type: 'bedrock',
    models: [],
    apiKeyAlias: 'AWS_ACCESS_KEY',
    getKeyUrl: 'https://console.aws.amazon.com/bedrock',
    notes: 'AWS Bedrock models',
  },
  {
    id: 'qwen',
    name: 'Alibaba Qwen',
    slug: 'qwen',
    type: 'direct',
    baseUrl: 'https://dashscope.aliyuncs.com/api/v1',
    models: ['qwen-turbo', 'qwen-plus', 'qwen-max'],
    apiKeyAlias: 'QWEN_API_KEY',
    getKeyUrl: 'https://bailian.console.aliyun.com',
    notes: 'Alibaba Qwen models',
  },
  {
    id: 'hunyuan',
    name: 'Tencent Hunyuan',
    slug: 'hunyuan',
    type: 'direct',
    baseUrl: 'https://hunyuan.tencentcloudapi.com',
    models: ['hunyuan-standard', 'hunyuan-lite'],
    apiKeyAlias: 'HUNYUAN_API_KEY',
    getKeyUrl: 'https://cloud.tencent.com/product/hunyuan',
    notes: 'Tencent Hunyuan models',
  },
  {
    id: 'glm',
    name: 'Zhipu GLM',
    slug: 'glm',
    type: 'direct',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    models: ['glm-4', 'glm-3-turbo'],
    apiKeyAlias: 'GLM_API_KEY',
    getKeyUrl: 'https://open.bigmodel.cn',
    notes: 'Zhipu GLM models',
  },
  {
    id: 'sensetime',
    name: 'SenseTime SenseNova',
    slug: 'sensetime',
    type: 'direct',
    baseUrl: 'https://api.sensenova.cn/v1',
    models: ['sensenova-xl', 'sensenova-l'],
    apiKeyAlias: 'SENSETIME_API_KEY',
    getKeyUrl: 'https://open.sensetime.com',
    notes: 'SenseTime SenseNova models',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    slug: 'deepseek',
    type: 'direct',
    baseUrl: 'https://api.deepseek.com/v1',
    models: ['deepseek-chat', 'deepseek-coder'],
    apiKeyAlias: 'DEEPSEEK_API_KEY',
    getKeyUrl: 'https://platform.deepseek.com',
    notes: 'DeepSeek models',
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    slug: 'moonshot',
    type: 'direct',
    baseUrl: 'https://api.moonshot.cn/v1',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    apiKeyAlias: 'MOONSHOT_API_KEY',
    getKeyUrl: 'https://platform.moonshot.cn',
    notes: 'Moonshot AI models',
  },
];
